# Generated by Django 6.0.1 on 2026-04-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='active',
            new_name='is_active',
        ),
    ]
