# Generated by Django 6.0.1 on 2026-05-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_rename_active_enrollment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='teacher',
        ),
    ]
