# Generated by Django 6.0.1 on 2026-05-29 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_review_rating'),
        ('enrollments', '0004_enrollment_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
    ]
