# Generated by Django 6.0.1 on 2026-04-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('general', 'General English'), ('business', 'Business English'), ('esp', 'English for Specific Purposes'), ('eap', 'English for Academic Purposes'), ('ib', 'IB English'), ('igcse', 'IGCSE English')], max_length=20),
        ),
    ]
